### ISSUE TITLE
layer setting per bone

### ISSUE THREAD

**Issue by Narazaka** [jetdog8808/Avatar-Armature-Collider#1]
This is a very wanted asset! I put it in my world YUTOROOM (bathroom + chill world) and it provides an immersive shower experience!(?)

And I want to collide some pickups by this system but colliding with fingers is not comfortable for grabbable pickups so I want to set layers for specific (finger) bones.
The "Collider size tweaks" category might be suitable for bone categorizing.

**Comment by jetdog8808** [comment]
The system is designed to act like the built in unity collider components, and adding support for setting sections to different layers would be convoluted.
For your situation there is a option to disable the finger bones. I also have plans to implement layer overrides.
If these options are not enough there is public api to get the fingers [collider](https://github.com/jetdog8808/Avatar-Armature-Collider/blob/main/Scripts/AvatarArmatureColliderSystem.cs#L727) and/or [rigidbody](https://github.com/jetdog8808/Avatar-Armature-Collider/blob/main/Scripts/AvatarArmatureColliderSystem.cs#L566) to change the layers.

Would any of these options work for you?

**Comment by Narazaka** [comment]
Cannot override the finger bone collider because the hand collider is needed for the shower particle collider and not for the pickup collider.
Layer override might be a good idea.

**Comment by jetdog8808** [comment]
Added Layer Override in V1.1
https://github.com/jetdog8808/Avatar-Armature-Collider/releases/tag/v1.1
