### ISSUE TITLE
collision with VRCObjectSync pickups problem

### ISSUE THREAD

**Issue by Narazaka** [jetdog8808/Avatar-Armature-Collider#4]
If AvatarArmatureColliders collide with VRCObjectSync pickup objects, ownership does not transfer to the player who has that AvatarArmatureColliders.
It is natural because AvatarArmatureColliders do not have VRCObjectSync and AllowCollisionOwnershipTransfer.

So collision with pickups whose owner is other player sometimes causes strange or unstable behavior.

**Comment by jetdog8808** [comment]
the AvatarCollider script could add a SetOwner method in the OnCollisionEnter event. My main concern is the performance of calling GetComponentInParent for every event.

**Comment by Narazaka** [comment]
I see...
Thank you to this so performant library. It is reasonable issue...

**Comment by jetdog8808** [comment]
Another concern was kinematic colliders calling OnCollisionEnter for static colliders. [Documentation shows it will only send events for dynamic colliders.](https://docs.unity3d.com/Manual/collider-types-interaction.html)

added a new component and option to toggle the ownership transfer: eeb807c432acf69103c97349905f65092546bee5
